### PR TITLE
feat: added php dependencies support

### PR DESCRIPTION
**Pull request by syarig**
I added php dependency support. (but php namespace-use only)

Also I changed behaver when checked for `dependencies > direct only` 

Could you review it.

## Feature change
- enabled `full-featres` support for php
- implemented parsing imported dependency and namespace dependency for php by php-parser 
- added src-php in example project
- changed behaver of dependencies when checked for `direct only`

### CODE REVIEW

**Comment by Bogdan-Lyashenko** [comment]
Hi, thanks for the contribution, I'll review this some time soon.

**Comment by Bogdan-Lyashenko** [comment]
Hey @syarig, when I ran it locally I got an error for chaining operator
`
Learning/codecrumbs/src/server/code-parse/language/php/dependencies.js:12
  phpNamespaces[entryPoint]?.importedModuleNames.forEach((moduleName) => {

SyntaxError: Unexpected token '.'`
                            
I guess you'll need to polyfill in or add version check for node version (preferably polyfill) in order to work everywhere. Thanks.

**Comment by syarig** [comment]
Hi @Bogdan-Lyashenko, Thank you for review.
Oh, I see...
I tried it on node 12 and it worked fine.

but, I thought I want to run it on docker and node version 14.
so, Added Dockerfile. What is your take on it?

You would run server-dev with the following command

```
docker build -tcodecrumbs-server. && docker run --rm -p 2018: 2018 -p 3018:3018 -it codecrumbs-server server-dev php
```

**Comment by nomura-kainos** [comment]
Is this PR in progress?
I also wanted this support, so I'm curious.

**Comment by Bogdan-Lyashenko** [comment]
Hey, sorry guys for being super slow on this one. I just merged it with few adjustments, new version is on npm now as well. @syarig thx for an amazing contrubution!

**Pull request merged**
